packageExtensions:
  '@firebase/auth@*':
    dependencies:
      '@firebase/app-types': '*'
      '@firebase/util': '*'
  '@firebase/database@*':
    dependencies:
      '@firebase/app': '*'
      '@firebase/app-types': '*'
  '@firebase/firestore@*':
    dependencies:
      protobufjs: '*'

yarnPath: .yarn/releases/yarn-rc.js
